sudo: required
language: minimal
git:
  depth: 2
services:
- docker
branches:
  only:
  - master
  - devel
env:
  global:
  - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/memote-webservice
  - IMAGE_TAG=${TRAVIS_BRANCH}
install:
- docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
- make setup
script:
- make flake8
- make isort
- make license
- make safety
- make test-travis
before_deploy:
- "./scripts/install_gcloud.sh"
- "./scripts/install_kubectl.sh"
- docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
- docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  on:
    all_branches: true
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    on_pull_requests: false
    rooms:
      - secure: "iFTbbYmDNymv3TYBEXkBYPuW2rCDetrVXvyl91MuiO0e+65IE915y9iUSQPmi52r6UFWcPpbIkOyYtFnTclJHSN8ccttdbftmjB8X1ZsXxsH3M6zwmfRCy0YAKYLVZFiBZLu2NHZ6Tuz33/XGjeX23O+fQpEA855PqePDVVOSZu1rgINg/yh6FDRmwkJ+88RAw9weXCLzJnGp6NcMVwzXOWIznz557yG9Oo/QzoIPrcC9rngN2awn6Ksnfmg6quMrBeQ8DS01+lhtsIeOFfHBbnucgrmgf6UGhZm/pmaiadKr423EzjCjqd7zA8ayD7+s7Vpi+m0LGLMgX+XRRtlU2fji2h+/B0FZZ3EiZSKWRlbg5QTbTOcuf4z8U8t9tdcHBxlM28EdJOIVUwQ2qpS0HbLIzc++Iz6fLyHvjZGnIDmdk2dkRhqyBxByQfFoeEmruH9OMFqbebWNbfG0CrxFzfmO0MdXrSHMGdq+OXJDD842otyDQqDEMAD5sa3/w+qFqJ5fBT3TeUr3QTYdqOki2PDkuqpsw3W+iUmQyHHyUUGrDLgbfU8DwV7iUXUswY4d/kbASnH0O7Ol/ih8dYH21zsrBdE0DtyXJHc9SI4luIsQ1XhjDsJL/kSvPyZZP6I27jq4V7iUqlOiDfdBst/kgmMicJMD2TvFY1p86nS0w4="