version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: opencobra/memote-webservice:${IMAGE_TAG:-latest}
    networks:
      default:
      opencobra:
        aliases:
          - memote-webservice
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/home/kaa/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/memote_webservice/wsgi.py
      - SCRIPT_NAME=/memote-webservice
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIS_URL=redis://cache:6379/0
    depends_on:
      - cache
    command: gunicorn -c gunicorn.py memote_webservice.wsgi:app
  cache:
    image: redis:4.0-alpine
    networks:
      default:
  worker:
    user: kaa
    image: opencobra/memote-webservice:${IMAGE_TAG:-latest}
    networks:
      default:
    volumes:
      - ".:/home/kaa/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - REDIS_URL=redis://cache:6379/0
    depends_on:
      - cache
    command: celery -A memote_webservice.tasks worker --loglevel=info
  flower:
    image: opencobra/memote-webservice:${IMAGE_TAG:-latest}
    depends_on:
      - cache
    networks:
      default:
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    volumes:
      - ".:/app"
    environment:
      - REDIS_URL=redis://cache:6379/0
    command: celery flower -A memote_webservice --broker=redis://cache:6379/0


# Additional services that the `web` service `depends_on` should usually only
# be on the default network and not exposed on the general network, i.e.,
# networks:
#   - default

networks:
  opencobra:
    external: true
