apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: memote-webservice
spec:
  tls:
  - hosts:
    - memote.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: memote.dd-decaf.eu
    http:
      paths:
      - path: /memote-webservice
        backend:
          serviceName: memote-webservice-production
          servicePort: 80
