kind: Service
apiVersion: v1
metadata:
  name: memote-webservice-production
spec:
  selector:
    app: memote-webservice
    env: production
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: flower
    protocol: TCP
    port: 5555
    targetPort: 5555
